services:
  goservice:
    container_name: template-service
    build: 
      context: .
    environment:
      - GRPC_PORT=14500
      - GRPC_TIMEOUT=24h
    ports:
      - 14500:14500
    networks:
      - shared-network
    

networks:
  shared-network:
    external: true